### ISSUE TITLE
"npm test" fails when running on Node.js 10+

### ISSUE THREAD

**Issue by onebytegone** [silvermine/lambda-utils#6]
When using Node.js 10 or greater, `npm test` will fail with the error:

```
$ npm test
> @silvermine/lambda-utils@0.1.0 test /home/travis/build/silvermine/lambda-utils
> istanbul cover ./node_modules/.bin/_mocha -- -R spec 'tests/**/*.test.js'
  event-unwrappers/s3-in-sns
/home/travis/build/silvermine/lambda-utils/node_modules/istanbul/lib/command/common/run-with-cover.js:239
                        console.error('=============================================================================');
                                ^
TypeError: console.error is not a function
    at process.<anonymous> (/home/travis/build/silvermine/lambda-utils/node_modules/istanbul/lib/command/common/run-with-cover.js:239:33)
    at Object.onceWrapper (events.js:273:13)
    at process.emit (events.js:187:15)
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```

Example: https://travis-ci.org/silvermine/lambda-utils/jobs/458534214

**Comment by onebytegone** [comment]
This commit might be of help: https://github.com/silvermine/apigateway-utils/commit/89d9eaeadc9b3208553b9724acf89474f4fec662
